### ISSUE TITLE
integration tests fail when run in parallel

### ISSUE THREAD

**Issue by fg-j** [paketo-community/miniconda#102]
A recurring problem for this buildpack is that the integration tests consistently hang on the Github Actions runners when run with `spec.Parallel()`. See [this test failure](https://github.com/paketo-community/miniconda/runs/2412261212?check_suite_focus=true) for an example. It only seems to occur on Azure GHA runners.

Upon investigation, it seems like this is something to do with the [miniconda installer script](https://github.com/paketo-community/miniconda/blob/ad46cbd9e07f58dbf8981457fc7262ac56882fef/buildpack.toml#L18) that the [buildpack runs](https://github.com/paketo-community/miniconda/blob/ad46cbd9e07f58dbf8981457fc7262ac56882fef/script_runner.go#L31) running into some sort of kernel mutex deadlock issue when run concurrently in multiple containers on the same GHA VM. Using [tmate](https://github.com/mxschmitt/action-tmate) to jump onto a hanging integration test run, a look at the docker daemon reveals hanging container(s) stuck during the buildpacks' `build` phase. `ps aux` inside a hanging container reveals that the miniconda installer process is stuck.

To quickly reproduce this problem:
1. Make a branch on this repo and open a PR with it, with the following changes:
    1. Add a [tmate step](https://github.com/mxschmitt/action-tmate) to the existing Integration Test github workflow (like [this](https://github.com/paketo-community/miniconda/blob/f6955474204dfe762f5c7ab287d1a1194329445f/.github/workflows/test-pull-request.yml#L48))
1. Trigger a GHA run (manually, with a commit, etc.)
1. Attach to the GHA runner with tmate
1. `docker pull paketobuildpacks/builder:0.1.100-base`
1. `docker run -it paketobuildpacks/builder:0.1.100-base /bin/bash`
1. Download the [script](https://github.com/paketo-community/miniconda/blob/f6955474204dfe762f5c7ab287d1a1194329445f/buildpack.toml#L18) specified in the `buildpack.toml` into the container.
1. Create an infinite loop running the script (which will install conda) and then uninstalling it:
    ```
    mkdir /layers/conda-installation
    while true; do /bin/bash /layers/downloaded-installer-script.sh -b -f -p /layers/conda-installation; rm -rf /layers/conda-installation/*; done
    ```

1. While that container is still running, start another container from the base builder `docker run -it paketobuildpacks/builder:0.1.100-base /bin/bash`, download the installer script, and start the same `while` loop.

1. You should see one of the loops lock up almost immediately, stuck on a `Unpacking payload...` step. The other loop will likely continue with no issues.

We suspect that the above behaviour causes integration tests to hang when run in parallel, since one test container blocks infinitely if another is also running the conda installation process at the same time.

It also seems like this issue can be reproduced by running many sequential builds. @ryanmoran has more context on that.

### Possible resolution

Upgrading to the miniconda 4.9.2 installer seems to resolve this issue -- following the steps outlined above with that script does _not_ produce this problem. We should upgrade the miniconda version in the buildpack (as #96 suggests) to fix the buildpack integration tests.

**Comment by ryanmoran** [comment]
I was able to get a similar reproduction by simply running `pack build` in a loop. Within a small number of iterations, the loop would stall as the buildpack would just hanging in its build process. After modifying the buildpack to print out the build output from the Miniconda installation script, I found that it was hanging at a point where the script was `Unpacking payload...`. While the script was hanging, I `docker exec`'d into that same container and took a look at what was happening. From `ps aux`, `strace`, and `gdb` probing, it appears that there is some thread contention issue with the Conda [constructor](https://github.com/conda/constructor) that is executed during the installation script resulting in deadlock.

I also found that updating the version of Miniconda to the `py38-4.9.2` installer resolved the issue. I was able to run the `pack build` loop for over 2 hours without any issue.
