### ISSUE TITLE
Restructure: Rename buildpack to miniconda and rewrite it

### ISSUE THREAD

**Issue by arjun024** [paketo-community/miniconda#72]
### Background
See [RFC 0001](https://github.com/paketo-community/python/blob/main/rfcs/0001-restructure.md) that outlines the proposed restructure of python family of buildpacks. 

### Proposal

* This repository should be renamed to `miniconda`.
* Rewrite using [packit](github.com/paketo-buildpacks/packit) library.
* The `miniconda` cnb should simply install [`miniconda3`](https://docs.conda.io/en/latest/miniconda.html).
* It must no longer run “conda env update” or “conda env create” commands.
* It must no longer require `procfile`, and no longer write a start command.
* The buildpack API should be as follows:
  * provides: `conda`
  * requires: none

**Comment by sophiewigmore** [comment]
Extra notes:

Please update the README and GoDoc to be consistent with buildpacks in this language family
Please use buildpack API 0.4 in the buildpack.toml

**Comment by ForestEckhardt** [comment]
@paketo-community/python-maintainers I will need someone to change the name of this repo to compile with this issue.

**Comment by shanks3012** [comment]
Currently, unable to run integration tests within github actions as they hang indefinitely. This will need to be resolved in order to progress the issue forward.

**Comment by arjun024** [comment]
Closed by #93
