### ISSUE TITLE
Update miniconda dependency by hand

### ISSUE THREAD

**Issue by ForestEckhardt** [paketo-community/miniconda#96]
Currently there is no automation to update the miniconda dependency, so for the time being this will need to be updated by hand.

**Comment by ryanmoran** [comment]
The Miniconda installer comes with a specific version of Python that it installs as the "root" Python installation. This is signified by the `pyXX` identifier on the Miniconda installation scripts (e.g. `Miniconda3-py37_4.8.2-Linux-x86_64.sh` is the Miniconda 4.8.2 installer using Python 3.7 as the "root" Python installation). Conda is capable of installing different versions of Python in different environments regardless of what "root" Python version is chosen. Therefore, we should only need to provide versions of Miniconda that correspond to a single "root" Python version. I propose that we go with 3.9 as it is the latest stable release version. This means that we would want to include the https://repo.anaconda.com/miniconda/Miniconda3-py39_4.9.2-Linux-x86_64.sh installer in the `buildpack.toml`

**Comment by sophiewigmore** [comment]
To update the version of miniconda by hand do the following steps:
1.  Go to https://repo.anaconda.com/miniconda/ and find the latest version of the miniconda script (at the bottom)
2. Update the `uri` field in the buildpack.toml file with the URL to the latest version found in step 1.
3. Calculate the SHA256 of the script and update the `sha256` field in the buildpack.toml
4.  Go to https://github.com/conda/conda/ releases and find the corresponding source release for the new version. Find the tarball that corresponds with that release and add the link to the `source` field in the buildpack.toml.
5.  Download and calculate the SHA256 of the related `tar.gz` artifact in the release, and update the `source_sha256` field in the buildpack.toml.
6. For the deprecation date, the date that is currently in the buildpack.toml corresponds to the Python version that is compatible with the Miniconda version, which is Python 3.7. **Our open question around this is if the deprecation date should be Python's deprecation date, or the actual Miniconda deprecation date?** Until this question is resolved, we should probably refrain from adding the deprecation date so it's not misleading.
